version: '3'

services:

  backend:
    image: node-typestack-starter
    environment:
    - SERVICE_PORTS=3000
    links:
    - mongo
    depends_on:
    - mongo

  grafana:
    image: grafana/grafana
    ports:
    - "3001:3000"
    links:
    - prometheus
  prometheus:
    build: prometheus
    ports:
    - "9090:9090"

   haproxy:
    image: dockercloud/haproxy
    links:
     - backend
    ports:
     - "3000:80"
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock

    mongo:
      image: mongo:3.4.2
      ports:
      - "27017:27017"
      volumes:
      - ./data/db:/data/db

volumes:
  dcs_data_dev:
