#Global configurations
global:
  scrape_interval:     5s # Set the scrape interval to every 5 seconds.
  external_labels:
    monitor: 'node-typestack-starter'

scrape_configs:
  - job_name: 'backend'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['backend:3000']
  - job_name: 'haproxy' 
    static_configs:
      - targets: ['haproxy_exporter:9101']
  - job_name: 'mongodb' 
    static_configs:
      - targets: ['mongodb_exporter:9216']
