#Global configurations
global:
  scrape_interval:     5s # Set the scrape interval to every 5 seconds.
  external_labels:
    monitor: 'microservices-monitor'

scrape_configs:
  - job_name: 'webshop-app'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['webshop:8080']